// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvKeavkPWAD-QJ7i0zUswIrEr51c_yp64',
    appId: '1:185155620231:web:f0b5a01de2562c651f5722',
    messagingSenderId: '185155620231',
    projectId: 'spade-attendance-app',
    authDomain: 'spade-attendance-app.firebaseapp.com',
    databaseURL: 'https://spade-attendance-app-default-rtdb.firebaseio.com',
    storageBucket: 'spade-attendance-app.firebasestorage.app',
    measurementId: 'G-0KHNQKY0N2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGz_yfY4Exom01aaFO_8qjGwGIkJP4YHI',
    appId: '1:185155620231:android:6f86a22d4d752c4d1f5722',
    messagingSenderId: '185155620231',
    projectId: 'spade-attendance-app',
    databaseURL: 'https://spade-attendance-app-default-rtdb.firebaseio.com',
    storageBucket: 'spade-attendance-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5yoX7Z4p1rAPCgWUcJQq10H3FNvqBTQQ',
    appId: '1:185155620231:ios:132ac8622efecb1b1f5722',
    messagingSenderId: '185155620231',
    projectId: 'spade-attendance-app',
    databaseURL: 'https://spade-attendance-app-default-rtdb.firebaseio.com',
    storageBucket: 'spade-attendance-app.firebasestorage.app',
    iosBundleId: 'com.example.spadeAttendenceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC5yoX7Z4p1rAPCgWUcJQq10H3FNvqBTQQ',
    appId: '1:185155620231:ios:132ac8622efecb1b1f5722',
    messagingSenderId: '185155620231',
    projectId: 'spade-attendance-app',
    databaseURL: 'https://spade-attendance-app-default-rtdb.firebaseio.com',
    storageBucket: 'spade-attendance-app.firebasestorage.app',
    iosBundleId: 'com.example.spadeAttendenceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCvKeavkPWAD-QJ7i0zUswIrEr51c_yp64',
    appId: '1:185155620231:web:cefa209bae4ae9cc1f5722',
    messagingSenderId: '185155620231',
    projectId: 'spade-attendance-app',
    authDomain: 'spade-attendance-app.firebaseapp.com',
    databaseURL: 'https://spade-attendance-app-default-rtdb.firebaseio.com',
    storageBucket: 'spade-attendance-app.firebasestorage.app',
    measurementId: 'G-PR8GSS0RKQ',
  );

}